import { getServerSession } from 'next-auth'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import './globals.css'
import Link from 'next/link'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log('session', session)
  return (
    <html lang="en">
      <body>
        <div className="navbar"> 
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link>
          {
            session == null ?
            <LoginBtn /> :
            <span>{session.user.name} <LogoutBtn /></span>
          }
          
        </div>    
        {children}
      </body>
    </html>
  )
}
